import ast
import shlex
import re
from typing import List, Dict, Any, Set, Tuple


class PythonASTSecurityVisitor(ast.NodeVisitor):
    """
    Real Python AST Visitor inspecting Python code generated by LLM agents or tool invocations.
    Detects dangerous calls (eval, exec, compile), malicious imports (subprocess, socket, pty),
    and destructive OS attribute calls (os.system, os.remove, shutil.rmtree).
    """
    DANGEROUS_CALLS = {"eval", "exec", "compile", "__import__"}
    DANGEROUS_MODULES = {"subprocess", "socket", "pty", "posix", "ctypes", "winreg"}
    DANGEROUS_ATTRIBUTES = {
        ("os", "system"), ("os", "popen"), ("os", "spawn"), ("os", "remove"),
        ("os", "unlink"), ("os", "rmdir"), ("subprocess", "Popen"),
        ("subprocess", "call"), ("subprocess", "run"), ("subprocess", "check_output"),
        ("shutil", "rmtree"), ("builtins", "eval"), ("builtins", "exec")
    }

    def __init__(self):
        self.findings: List[Dict[str, Any]] = []
        self.imported_modules: Set[str] = set()

    def visit_Import(self, node: ast.Import):
        for alias in node.names:
            self.imported_modules.add(alias.name)
            if alias.name in self.DANGEROUS_MODULES:
                self.findings.append({
                    "rule": "SEC_AST_001_DANGEROUS_IMPORT",
                    "severity": "HIGH",
                    "detail": f"Direct import of restricted system module '{alias.name}'",
                    "line": node.lineno
                })
        self.generic_visit(node)

    def visit_ImportFrom(self, node: ast.ImportFrom):
        module = node.module or ""
        self.imported_modules.add(module)
        if module in self.DANGEROUS_MODULES:
            self.findings.append({
                "rule": "SEC_AST_001_DANGEROUS_IMPORT",
                "severity": "HIGH",
                "detail": f"Import from restricted system module '{module}'",
                "line": node.lineno
            })
        self.generic_visit(node)

    def visit_Call(self, node: ast.Call):
        # 1. Check direct name calls: eval(...), exec(...)
        if isinstance(node.func, ast.Name):
            if node.func.id in self.DANGEROUS_CALLS:
                self.findings.append({
                    "rule": "SEC_AST_002_DYNAMIC_EXECUTION",
                    "severity": "CRITICAL",
                    "detail": f"Invocation of dynamic code execution builtin '{node.func.id}'",
                    "line": node.lineno
                })
        # 2. Check attribute calls: os.system(...), subprocess.Popen(...)
        elif isinstance(node.func, ast.Attribute):
            attr_name = node.func.attr
            if isinstance(node.func.value, ast.Name):
                module_name = node.func.value.id
                if (module_name, attr_name) in self.DANGEROUS_ATTRIBUTES:
                    self.findings.append({
                        "rule": "SEC_AST_003_DESTRUCTIVE_OS_CALL",
                        "severity": "CRITICAL",
                        "detail": f"Dangerous method call '{module_name}.{attr_name}'",
                        "line": node.lineno
                    })
        self.generic_visit(node)


class CommandASTAnalyzer:
    """
    Analyzes shell command pipelines and Python tool scripts for security violations.
    Combines AST inspection with shell subshell extraction.
    """
    def __init__(self):
        self.control_operators = {"&&", "||", ";", "|", "&"}

    def analyze_python_source(self, code_str: str) -> Tuple[bool, List[Dict[str, Any]]]:
        """
        Parses Python code into an AST and analyzes it for dangerous constructs.
        Returns (is_clean, findings_list).
        """
        try:
            tree = ast.parse(code_str)
        except SyntaxError as e:
            return False, [{
                "rule": "SEC_AST_000_SYNTAX_ERROR",
                "severity": "MEDIUM",
                "detail": f"Failed to parse AST (SyntaxError: {e})",
                "line": getattr(e, "lineno", 1)
            }]

        visitor = PythonASTSecurityVisitor()
        visitor.visit(tree)
        is_clean = len(visitor.findings) == 0
        return is_clean, visitor.findings

    def extract_subshells(self, command: str) -> List[str]:
        """
        Extracts nested subshell scripts wrapped in $() or backticks.
        """
        subshells = []
        # Matches $(...)
        for match in re.finditer(r"\$\(([^)]+)\)", command):
            subshells.append(match.group(1).strip())
        # Matches `...`
        for match in re.finditer(r"`([^`]+)`", command):
            subshells.append(match.group(1).strip())
        return subshells

    def parse_command_segments(self, command: str) -> List[List[str]]:
        """
        Parses a shell command line string into segmented command tokens.
        """
        try:
            tokens = shlex.split(command)
        except Exception:
            tokens = command.split()

        segments = []
        current_segment = []
        for token in tokens:
            if token in self.control_operators:
                if current_segment:
                    segments.append(current_segment)
                    current_segment = []
            else:
                current_segment.append(token)

        if current_segment:
            segments.append(current_segment)

        return segments
